version: "3.8"

services:
  schoolmoney-minio:
    restart: unless-stopped
    image: quay.io/minio/minio:RELEASE.2025-03-12T18-04-18Z
    container_name: schoolmoney-minio
    command: server /data --console-address ":9501"
    volumes:
      - schoolmoney_minio_data:/data
    environment:
      MINIO_ROOT_USER: ${STORAGE_S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${STORAGE_S3_SECRET_KEY}
    ports:
      - "9500:9000"     # MinIO API
      - "9501:9501"     # MinIO Console
    networks:
      - schoolmoney_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  schoolmoney-psql:
    restart: unless-stopped
    image: postgres:17.4-alpine3.21
    container_name: schoolmoney-psql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_DB=${POSTGRES_DB:?err}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - schoolmoney_postgres_data:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    networks:
      - schoolmoney_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  schoolmoney-app:
    restart: unless-stopped
    container_name: schoolmoney-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Database Configuration
      - SPRING_DATASOURCE_URL=jdbc:postgresql://schoolmoney-psql:5432/${POSTGRES_DB:?err}
      - POSTGRES_URL=jdbc:postgresql://schoolmoney-psql:5432/${POSTGRES_DB:?err}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:?err}
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}

      # CORS Configuration
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}

      # Mailgun Configuration
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - MAILGUN_CLIENT_DOMAIN=${MAILGUN_CLIENT_DOMAIN}
      - MAILGUN_FROM=${MAILGUN_FROM}
      - MAIL_FRONTEND_URL=${MAIL_FRONTEND_URL}

      # S3 / MinIO Configuration
      - STORAGE_S3_BUCKET_NAME=${STORAGE_S3_BUCKET_NAME}
      - STORAGE_S3_SECRET_KEY=${STORAGE_S3_SECRET_KEY}
      - STORAGE_S3_ACCESS_KEY=${STORAGE_S3_ACCESS_KEY}
      - STORAGE_S3_ENDPOINT=http://files.schoolmoney.local
      - MINIO_ENDPOINT=http://schoolmoney-minio:9000
      - MINIO_ACCESS_KEY=${STORAGE_S3_ACCESS_KEY}
      - MINIO_SECRET_KEY=${STORAGE_S3_SECRET_KEY}
    ports:
      - "8081:8081"
    depends_on:
      schoolmoney-psql:
        condition: service_healthy
      schoolmoney-minio:
        condition: service_healthy
    networks:
      - schoolmoney_network

volumes:
  schoolmoney_postgres_data:
  schoolmoney_minio_data:

networks:
  schoolmoney_network:
    name: schoolmoney_network
    driver: bridge
